# Generated by Django 4.2.5 on 2023-10-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_username_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('protected', 'Protected'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
